### ISSUE TITLE
Review of 20220502 document

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/UAT-as-upstream#2]
I have just been looking over this revision to the Note.. a couple comments and questions.

Minor:
1. the architecture diagram is missing
2. Section 2, paragraph 1:  "Since it is available under CC-BY-SA,".  I gathered that "CC-BY-SA" was a license from the context, but including the word 'license' would be a smidge more clear.
3. Section 2, paragraph 2:  There are a lot of acronyms here, but 'SC' for 'steering committee' gave me a brief pause.

Question/Query:
Section 3:  I don't know about the UAT or any of the earlier discussions around the translation tool, so I'm assuming this has been discussed within semantics.  I am just curious about the reasoning.
    * The UAT has gone to numeric IDs for the concepts, which the text notes "is certainly a positive step in a multilingual environment"
    * The translator utility will replace all non-alphanumeric characters to a single dash.
The UAT has the flexibility to use non-English characters (umlaut, accents, other ) and a simple reading of the translation algorithm implies these would be converted to '-', which would make the result somewhat ugly.  Even the example case of "Hubble's Law" -> 'hubble-s-law' is a bit awkward.

I'm also curious about the case where the 'Preferred Label' changes for a given ID.  Does the IVOA vocabulary then retain 2 labels indefinitely?  This sounds like the IVOA vocabulary is not trying to 'sync' with the UAT, but harvest it for new terms.. is that right?

**Comment by msdemlei** [comment]
Thanks for the review.

On Tue, Jun 07, 2022 at 08:58:20AM -0700, Mark Cresitello-Dittmar wrote:
> Minor:
> 1. the architecture diagram is missing

Endorsed notes so far didn't have architecture diagrams.  In
particular, they don't live on the architecture diagram themselves,
which I *think* is a sane policy.  Given things like the UDF
catalogue, we might reconsider this, but I guess that would be
material for a TCG meeting.

Will you bring it up there?

> 2. Section 2, paragraph 1:  "Since it is available under
> CC-BY-SA,".  I gathered that "CC-BY-SA" was a license from the
> context, but including the word 'license' would be a smidge more
> clear.

Added "licence" in PR #3.

> 3. Section 2, paragraph 2:  There are a lot of acronyms here, but
> 'SC' for 'steering committee' gave me a brief pause.

Formally introducing the abbreviation in PR #3.

> The UAT has the flexibility to use non-English characters (umlaut,
> accents, other ) and a simple reading of the translation algorithm
> implies these would be converted to '-', which would make the
> result somewhat ugly.  Even the example case of "Hubble's Law" ->
> 'hubble-s-law' is a bit awkward.

The concrete translation from labels (which are the same for the
upstream and the IVOA UAT, of course) to the IVOA-internal
identifiers can still be changed.  The concrete mapping currently
proposed has been chosen because I believe it introduces the least
trouble with what I believe will be common search patterns in
RegTAP's rr.subject table, where it's preferable if "hubble" is a
token rather than, say, "hubbles".

Note that proper user agents should generally translate these
identifiers to the labels anyway, so outside of manually crafting
RegTAP ADQL and inspecting its results in TOPCAT, ordinary users
won't be confronted with these strings anyway.

> I'm also curious about the case where the 'Preferred Label' changes
> for a given ID.  Does the IVOA vocabulary then retain 2 labels
> indefinitely?  This sounds like the IVOA vocabulary is not trying
> to 'sync' with the UAT, but harvest it for new terms.. is that
> right?

No.  We follow the preferred label.  It is the identifier that does
not change; diverging identifiers and labels are not terribly pretty,
but unless there is a major desaster (where a concept really changes
its meaning, which of course should not happen) the two should
roughly be synonyms, and hence it ought not cause major confusion
either.

If you have advice as to where I could more clearly make these
points, I'll certainly be grateful; I'd push changes resulting from
that into PR#3, too.

**Comment by mcdittmar** [comment]
> Thanks for the review.
> On Tue, Jun 07, 2022 at 08:58:20AM -0700, Mark Cresitello-Dittmar wrote: Minor: 1. the architecture diagram is missing
> Endorsed notes so far didn't have architecture diagrams. In particular, they don't live on the architecture diagram themselves, which I *think* is a sane policy. Given things like the UDF catalogue, we might reconsider this, but I guess that would be material for a TCG meeting. Will you bring it up there?

Just to be clear, I was not advocating that the Note should have an architecture diagram, merely pointing out that the uploaded HTML page has the section (1.1) and a big empty box where 'role_diagram.svg' should be.  I assume this is a simple case of the image not being delivered with the html.

If endorsed notes typically don't have an architecture diagram, perhaps that section should be removed.

**Comment by msdemlei** [comment]
PR #3, I hope, has addressed the issues raised here.  Thanks!

**Comment by msdemlei** [comment]
On Tue, Jun 21, 2022 at 08:35:39AM -0700, Mark Cresitello-Dittmar wrote:
> Just to be clear, I was not advocating that the Note should have an
> architecture diagram, merely pointing out that the uploaded HTML
> page has the section (1.1) and a big empty box where
> 'role_diagram.svg' should be.  I assume this is a simple case of
> the image not being delivered with the html.

Oops.  Thanks for catching that.  I had entirely forgotten that I
*had* prepared an architecture diagram here (I think my reasoning was
that the UAT adoption note non-trivially sits between Registry and
Semantics).  I'll fix the upload.
